In [35]:
import pennylane as qml
import pennylane.numpy as np

def encode(i, j, k):
    """
    Quantum encoding function. It must act only on the first two qubits.
    This function does not return anything, it simply applies gates.

    Args:
        i, j, k (int): The three encoding bits. They will take the values 1 or 0.

    """
    
    # Put your code here #
    if i == 1:
        qml.PauliZ(wires=[0])
    if j == 1:
        qml.PauliX(wires=[1])
    if k == 1:
        qml.PauliX(wires=[0])
    

def decode():
    """
    Quantum decoding function. It can act on the three qubits.
    This function does not return anything, it simply applies gates.
    """

    # Put your code here #
    qml.CNOT(wires=[2,1])
    qml.CNOT(wires=[2,0])
    qml.Hadamard(wires=[2])
    qml.SWAP(wires=[0,2])

dev = qml.device("default.qubit", wires=3)

@qml.qnode(dev)
def circuit(i, j, k):
    """
    Circuit that generates the complete communication protocol.

    Args:
        i, j, k (int): The three encoding bits. They will take the value 1 or 0.
    """

    # We prepare the state 1/sqrt(2)(|000> + |111>)
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.CNOT(wires=[0, 2])

    # Zenda encodes the bits
    encode(i, j, k)

    # Reece decode the information
    decode()

    return qml.probs(wires=range(3))


# These functions are responsible for testing the solution.



def run(test_case_input: str) -> str:

    return None

def check(solution_output: str, expected_output: str) -> None:

    for i in range(2):
        for j in range(2):
            for k in range(2):
                print(i,j,k)
                print(circuit(i,j,k), [4 * i + 2 * j + k])
                assert np.isclose(circuit(i, j , k)[4 * i + 2 * j + k],1)

                dev = qml.device("default.qubit", wires=3)

                @qml.qnode(dev)
                def circuit2(i, j, k):
                    encode(i, j, k)
                    return qml.probs(wires=range(3))

                circuit2(i, j, k)
                ops = circuit2.tape.operations

                for op in ops:
                    assert not (2 in op.wires), "Invalid connection between qubits."


test_cases = [['No input', 'No output']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

Running test case 0 with input 'No input'...
0 0 0
[1. 0. 0. 0. 0. 0. 0. 0.] [0]
0 0 1
[0. 1. 0. 0. 0. 0. 0. 0.] [1]
0 1 0
[0. 0. 1. 0. 0. 0. 0. 0.] [2]
0 1 1
[0. 0. 0. 1. 0. 0. 0. 0.] [3]
1 0 0
[0. 0. 0. 0. 1. 0. 0. 0.] [4]
1 0 1
[0. 0. 0. 0. 0. 1. 0. 0.] [5]
1 1 0
[0. 0. 0. 0. 0. 0. 1. 0.] [6]
1 1 1
[0. 0. 0. 0. 0. 0. 0. 1.] [7]
Correct!


**States**
# |000>, |001>, |010>, |011>, |100>, |101>, |110>, |111>
**Associated circuit**
https://algassert.com/quirk#circuit={%22cols%22:[[%22H%22],[%22%E2%80%A2%22,%22X%22],[%22%E2%80%A2%22,1,%22X%22],[%22X%22],[%22Z%22],[%22%E2%80%A6%22,%22%E2%80%A6%22],[%22Bloch%22,%22Bloch%22],[%22Density3%22],[],[],[%22Chance3%22],[%22%E2%80%A6%22,%22%E2%80%A6%22],[1,%22X%22,%22%E2%80%A2%22],[%22X%22,1,%22%E2%80%A2%22],[1,1,%22H%22],[%22Density3%22]]}